### ISSUE TITLE
gdnative api change on godot tip

### ISSUE THREAD

**Issue by capnm** [ShadowApex/godot-go#29]
See the karofel's comment https://github.com/godotengine/godot/issues/12897

The python bindings I think, use now the wrapper  https://github.com/godotengine/godot/blob/master/modules/gdnative/SCsub#L246 (scons gdnative_wrapper=yes)

I tried to change the Go bindings, but even that seems to be currently somewhere down the gdnative road broken. So far I managed to run my Go code only as a (-buildmode=c-archive) static module :-(

**Comment by ShadowApex** [comment]
I just pushed changes that should make it compatible with the new version. I also included an example Godot project in the examples.

You should be able to test it out with the following:
```bash
cd examples/pong
make
godot
```

**Comment by capnm** [comment]
Great that you are working on this!

I've linked in the project folder the latest headers from the godot source to `godot_headers`
and got it to compile with [git.diff.txt](https://github.com/ShadowApex/godot-go/files/1530975/git.diff.txt) (godot tip 03c1b6be)

The problem still seems to remain the same:
`libgodot.so: undefined symbol: godot_vector3_is_normalized`
also you can't call e.g.
`isNormalized := C.godot_vector3_is_normalized(v.vector3)`
because the godot api doesn't export those symbols any more.

**Comment by ShadowApex** [comment]
This should be resolved now with the new changes and should be compatible with Godot 3.0 release.
